from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
from datetime import datetime
import io


def generate_pdf_report(result: dict, location: str, language: str) -> bytes:
    """
    Builds a downloadable PDF version of the MedBridge analysis,
    matching the on-screen report (medicines, explanations,
    pharmacy guidance, reminders).
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        topMargin=0.6 * inch,
        bottomMargin=0.6 * inch,
    )
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "TitleStyle", parent=styles["Title"], textColor=colors.HexColor("#2c7a7b")
    )
    heading_style = ParagraphStyle(
        "HeadingStyle", parent=styles["Heading2"], textColor=colors.HexColor("#2c7a7b"),
        spaceBefore=12, spaceAfter=4
    )
    body_style = ParagraphStyle(
        "BodyStyle", parent=styles["Normal"], fontSize=10, leading=14
    )
    meta_style = ParagraphStyle(
        "MetaStyle", parent=styles["Normal"], fontSize=9, textColor=colors.grey
    )

    story = []

    # --- Header ---
    story.append(Paragraph("MedBridge Agent — Prescription Report", title_style))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        f"Generated: {datetime.now().strftime('%d %b %Y, %I:%M %p')} | "
        f"Location: {location} | Language: {language}",
        meta_style
    ))
    story.append(Spacer(1, 4))
    story.append(Paragraph(
        "🔒 This report was generated from a prescription image processed in-memory. "
        "No personal data was stored on the server.",
        meta_style
    ))
    story.append(Spacer(1, 16))

    if result.get("doctor_notes"):
        story.append(Paragraph("Doctor's Notes", heading_style))
        story.append(Paragraph(result["doctor_notes"], body_style))
        story.append(Spacer(1, 10))

    # --- Medicines summary table ---
    table_data = [["Medicine", "Dosage", "Frequency", "Duration"]]
    for med in result["medicines"]:
        table_data.append([
            med.get("medicine", "-"),
            med.get("dosage", "-"),
            med.get("frequency", "-"),
            med.get("duration", "-"),
        ])

    table = Table(table_data, colWidths=[1.8 * inch, 1.2 * inch, 1.8 * inch, 1.2 * inch])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2c7a7b")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f0f9f9")]),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(table)
    story.append(Spacer(1, 16))

    # --- Per-medicine detail ---
    for med in result["medicines"]:
        story.append(Paragraph(f"💊 {med.get('medicine', 'Unknown')}", heading_style))

        story.append(Paragraph("<b>What is this medicine?</b>", body_style))
        story.append(Paragraph(med.get("explanation", "-").replace("\n", "<br/>"), body_style))
        story.append(Spacer(1, 6))

        story.append(Paragraph("<b>Where to buy?</b>", body_style))
        story.append(Paragraph(med.get("pharmacy_info", "-").replace("\n", "<br/>"), body_style))
        story.append(Spacer(1, 6))

        story.append(Paragraph("<b>Reminder</b>", body_style))
        reminder_text = med.get("reminder", "-").strip().replace("\n", "<br/>")
        story.append(Paragraph(reminder_text, body_style))
        story.append(Spacer(1, 14))

    # --- Footer disclaimer ---
    story.append(Spacer(1, 10))
    story.append(Paragraph(
        "<i>Disclaimer: This report is generated by an AI agent for informational "
        "purposes only and does not replace professional medical advice. "
        "Always consult your doctor or pharmacist before making medication decisions.</i>",
        meta_style
    ))

    doc.build(story)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes